In [21]:
#Importamos todo lo necesario
import random 
from deap import base, creator, tools, algorithms
import numpy
import operator
import copy

In [2]:
#Definimos como funciona cada tipo de puerta
def AND_GATE(input1,input2):
    if input1 == 1 and input2 == 1:
        return 1
    else:
        return 0



def NAND_GATE(input1,input2):
    if input1 == 1 and input2 == 1:
        return 0
    else:
        return 1


def OR_GATE(input1,input2):
    if input1 == 1:
        return 1
    elif input2 == 1:
        return 1
    else:
        return 0


def NOT_GATE(input1):
    if input1 == 1:
        return 0
    else:
        return 1
    
def XOR_GATE (input1,input2):
    if input1==1 and input2==0:
        return 1
    elif input1==0 and input2==1:
        return 1
    else:
        return 0

In [3]:
#Método para averiar una puerta
def averiar(circuito,i,j):
    if circuito[i][j]!=6:
        circuito[i][j]=6
    return circuito

In [4]:
#Este método toma un input y un circuito dado y construye una matriz output
#Esta matriz contiene la salida de todas las puertas del circuito, conectadas aleatoriamente
#Esto hace que sea útil si el circuito generado es aleatorio
#Por tanto, la última fila representa el output real del circuito introducido.
#El parámetro "muestra" sirve para pedir al método que imprima las conexiones o no.
#Si en vez de conexiones aleatorias quisieramos fijarlas hariamos lo siguiente:
#Un método que recibiera dos circuitos (el original y una variación de este) y un input
#Para cada puerta del circuito original:
#Si es igual en el circuito variación -> Se mantienen las mismas conexiones
#Si es distinta -> Se generan conexiones aleatorias para esa puerta
def simula_circuito(circuit_input,circuito,muestra):
        random.seed(12345)
        n=len(circuito)
        m=len(circuito[0])
        salidas=numpy.zeros((n,m))
        array_input=circuit_input
        salida_puertas=numpy.vstack((circuit_input,salidas))
        for i in range(1,n+1):
            for j in range(0,m):
                if (i==1) and (circuito[i-1][j]==1):
                    uno=random.randint(0,m-1)
                    dos=random.randint(0,m-1)
                    salida_puertas[i][j]=AND_GATE((array_input[uno]),(array_input[dos]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Input["+str(uno)+"] AND Input["+str(dos)+"]")
                elif (i==1) and (circuito[i-1][j]==2):
                    uno=random.randint(0,m-1)
                    dos=random.randint(0,m-1)
                    salida_puertas[i][j]=XOR_GATE((array_input[uno]),(array_input[dos]))
                    print("["+str(i)+"]"+"["+str(j)+"] = " + "Input["+str(uno)+"] XOR Input["+str(dos)+"]")
                elif (i==1) and (circuito[i-1][j]==3):
                    uno=random.randint(0,m-1)
                    dos=random.randint(0,m-1)
                    salida_puertas[i][j]=OR_GATE((array_input[uno]),(array_input[dos]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Input["+str(uno)+"] OR Input["+str(dos)+"]")
                elif (i==1) and (circuito[i-1][j]==4):
                    uno=random.randint(0,m-1)
                    dos=random.randint(0,m-1)
                    salida_puertas[i][j]=NAND_GATE((array_input[uno]),(array_input[dos]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Input["+str(uno)+"] NAND Input["+str(dos)+"]")
                elif (i==1) and (circuito[i-1][j]==5):
                    uno=random.randint(0,m-1)
                    salida_puertas[i][j]=NOT_GATE((array_input[uno]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + " NOT Input["+str(uno)+"]")
                elif (i==1) and (circuito[i-1][j]==6):
                    salida_puertas[i][j]=0
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Rota")
                elif (i>1) and (circuito[i-1][j]==1):
                    uno=random.randint(i-2,i-1)
                    dos=random.randint(0,m-1)
                    tres=random.randint(i-2,i-1)
                    cuatro=random.randint(0,m-1)
                    salida_puertas[i][j]=AND_GATE((salida_puertas[uno][dos]),(salida_puertas[tres][cuatro]))
                    if(muestra==True):
                        print("["+str(i)+"]["+str(j)+"] = Salida["+str(uno)+"]["+str(dos)+"] AND Salida["+str(tres)+"]["+str(cuatro)+"]")
                elif (i>1) and (circuito[i-1][j]==2):
                    uno=random.randint(i-2,i-1)
                    dos=random.randint(0,m-1)
                    tres=random.randint(i-2,i-1)
                    cuatro=random.randint(0,m-1)
                    salida_puertas[i][j]=XOR_GATE((salida_puertas[uno][dos]),(salida_puertas[tres][cuatro]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Salida["+str(uno)+"]["+str(dos)+"] XOR Salida["+str(tres)+"]["+str(cuatro)+"]")
                elif (i>1) and (circuito[i-1][j]==3):
                    uno=random.randint(i-2,i-1)
                    dos=random.randint(0,m-1)
                    tres=random.randint(i-2,i-1)
                    cuatro=random.randint(0,m-1)
                    salida_puertas[i][j]=OR_GATE((salida_puertas[uno][dos]),(salida_puertas[tres][cuatro]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Salida["+str(uno)+"]["+str(dos)+"] OR Salida["+str(tres)+"]["+str(cuatro)+"]")
                elif (i>1) and (circuito[i-1][j]==4):
                    uno=random.randint(i-2,i-1)
                    dos=random.randint(0,m-1)
                    tres=random.randint(i-2,i-1)
                    cuatro=random.randint(0,m-1)
                    salida_puertas[i][j]=NAND_GATE((salida_puertas[uno][dos]),(salida_puertas[tres][cuatro]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "Salida["+str(uno)+"]["+str(dos)+"] NAND Salida["+str(tres)+"]["+str(cuatro)+"]")
                elif (i>1) and (circuito[i-1][j]==5):
                    uno=random.randint(i-2,i-1)
                    dos=random.randint(0,m-1)
                    salida_puertas[i][j]=NOT_GATE((salida_puertas[uno][dos]))
                    if(muestra==True):
                        print("["+str(i)+"]"+"["+str(j)+"] = " + "NOT Salida["+str(uno)+"]["+str(dos)+"]")
                elif (i>1) and (circuito[i-1][j]==6):
                    salida_puertas[i][j]=0
                    if(muestra==True):
                        print("["+str(i)+"]["+str(j)+"]= Rota")
        output_total=numpy.zeros(m)
        for l in range(0,m):
            output_total[l]=(salida_puertas[n][l])
        if muestra==False:
            return output_total

In [5]:
#Vamos a definir un método que compare 2 outputs 
#Este método nos dirá si ambos son iguales, o en caso contrario, cúanto se parecen
def compara_salida(output1,output2):
    tamaño_salida=len(output1)
    parecido=0
    for i in range(0,tamaño_salida):
        if(output1[i]==output2[i]):
            parecido=1+parecido
        else:
            parecido=parecido
    return parecido/tamaño_salida

In [6]:
#Nuestro objetivo será maximizar el parecido entre el output ideal y el obtenido
creator.create('Fitness', base.Fitness, weights=(1.0,)) 

In [7]:
creator.create('Individuo', list, fitness = creator.Fitness)

In [8]:
#Creamos una Toolbox para almacenar todo lo que necesitemos
t_box = base.Toolbox()

In [9]:
#Cromosomas binarios que representan qué puertas se van a cambiar y  cuales no
t_box.register('gen', random.randint, 0, 1)

In [22]:
M = int(input("Número de capas del circuito: "))
N=int(input("Puertas por capa: "))
print("Circuito generado de " + str(M) + " capas de " + str(N) + " puertas:")
random.seed(12345)  # Semilla para el mecanismo de generación de números aleatorios
for _ in range((N*M)): #cada puerta consta de un gen para el tipo puerta y otros dos genes para las conexiones
    print(t_box.gen()) #dame NxM genes

Número de capas del circuito: 4
Puertas por capa: 4
Circuito generado de 4 capas de 4 puertas:
1
0
1
1
0
1
1
0
1
0
1
1
0
0
1
0


In [11]:
#Definimos que los individuos tengan N*M genes, representando versiones del circuito
#con distintas puertas
t_box.register('individuo', tools.initRepeat,
                              container=creator.Individuo, func=t_box.gen, n=(N*M))

In [12]:
#Definimos una población de 10 individuos
t_box.register('población', tools.initRepeat,
                              container=list, func=t_box.individuo, n=10)

In [13]:
#Definimos un fenotipo por el cual cada 1 en un individuo cambie una puerta del circuito
#dado por otra puerta aleatoria (incluida una averiada ya que el AG no sabe cual está rota)
def fenotipo(individuo):
    random.seed(12345)
    n=len(circuito_1)
    m=len(circuito_1[0])
    individuo_trans=numpy.array(individuo).reshape(n,m)
    circuito_fenotipo=copy.deepcopy(circuito_roto)
    for i in range(0,n):
        for j in range(0,m):
            if (individuo_trans[i][j]==1):
                circuito_fenotipo[i][j]=random.randint(1,6)
    return circuito_fenotipo
                
#Definimos un método de evaluación que compare la salida del circuito alternativo con
#la del fenotipo dado
def evaluar_individuo(individuo,):
    individuo_fen=fenotipo(individuo)
    kll=len(inputs)
    cal=0
    for i in range(0,kll):
        cal = cal + (abs(compara_salida(simula_circuito(inputs[i],circuito_1,False),(simula_circuito(inputs[i],individuo_fen,False)))))
    return (abs(cal),)
t_box.register('evaluate', evaluar_individuo)

In [14]:
#Definimos un método de mutar y uno de cruzar los genes de dos individuos
t_box.register('mate', tools.cxOnePoint)
t_box.register('mutate', tools.mutFlipBit, indpb=0.5)
# indpb es la probabilidad de mutación de cada gen del cromosoma

In [15]:
t_box.register('select', tools.selTournament, tournsize=3)

In [16]:
# Estadísticas sobre el fitness de los individuos: mínimo, media y máximo
# Nota: usamos para ello las funciones correspondientes de numpy, porque los
# valores de fitness están guardados en tuplas
estadísticas = tools.Statistics(lambda ind: ind.fitness.values)
estadísticas.register("mínimo", numpy.min)
estadísticas.register("media", numpy.mean)
estadísticas.register("máximo", numpy.max)

# Salón de la fama para recopilar los tres mejores individuos de todas las generaciones
salón_fama = tools.HallOfFame(3)

In [23]:
#Vamos a definir un circuito base:
n=4
m=4
circuito_1 = numpy.zeros((n,m))
random.seed(12345)
for i in range(0,n):
    for j in range(0,m):
        circuito_1[i][j]=random.randint(1,5)
print("Circuito: \n" + str(circuito_1))

#Creamos dos arrays: uno lleno de inputs y otro de sus correspondientes outputs
inputs=[]
outputs=[]
inputs.append([0,0,0,0])
inputs.append([0,0,0,1])
inputs.append([0,0,1,0])
inputs.append([1,1,0,0])


kl=len(inputs)
for i in range(0,kl):
    outputs.append((simula_circuito(inputs[i],circuito_1,False)))


Circuito: 
[[4. 1. 3. 3.]
 [2. 3. 5. 4.]
 [2. 3. 1. 4.]
 [3. 5. 2. 5.]]


In [24]:
print("Conexiones: \n")
simula_circuito(inputs[0],circuito_1,True)

Conexiones: 

[1][0] = Input[3] NAND Input[0]
[1][1] = Input[2] AND Input[2]
[1][2] = Input[1] OR Input[2]
[1][3] = Input[3] OR Input[1]
[2][0] = Salida[1][0] XOR Salida[1][2]
[2][1] = Salida[0][1] OR Salida[1][0]
[2][2] = NOT Salida[1][1]
[2][3] = Salida[0][1] NAND Salida[0][1]
[3][0] = Salida[2][2] XOR Salida[1][3]
[3][1] = Salida[2][0] OR Salida[2][0]
[3][2] = Salida[1][1] AND Salida[1][2]
[3][3] = Salida[1][3] NAND Salida[1][1]
[4][0] = Salida[3][1] OR Salida[3][0]
[4][1] = NOT Salida[2][0]
[4][2] = Salida[3][1] XOR Salida[2][2]
[4][3] = NOT Salida[3][1]


In [19]:
#Vamos a averiar un par de puertas y a ver si influye en la nueva salida
#Recordar que hay que hacer una copia del circuito que vamos a averiar
#De esta forma, tendremos por un lado el circuito estropeado y por otro el circuito ideal
#Esto se debe a que las asignaciones "=" en Python hacen que al modificar un objeto,
#el otro también se modifique. Esto dejaría dos circuitos averiados y no serviría
circuito_roto = copy.deepcopy(circuito_1)
averiar(circuito_roto,0,1)
averiar(circuito_roto,1,1)

array([[4., 6., 3., 3.],
       [2., 6., 5., 4.],
       [2., 3., 1., 4.],
       [3., 5., 2., 5.]])

In [20]:
población_inicial = t_box.población()
población, registro = algorithms.eaSimple(población_inicial,
                                          t_box,
                                          cxpb=0.5, # Probabilidad de que dos individuos contiguos se crucen
                                          mutpb=0.8, # Probabilidad de que un individuo mute
                                          ngen=20, # Número de generaciones
                                          stats=estadísticas,
                                          halloffame=salón_fama)
print('Las tres mejor soluciones encontradas han sido:')
for individuo in salón_fama:
    print(individuo, t_box.evaluate(individuo))
    print("\n Lo que se traduce en el siguiente circuito: \n" + str(fenotipo(individuo)))
    print( str(simula_circuito(inputs[0],fenotipo(individuo),True)))
    lg=(len(inputs))
    res=0
    for i in range(0,lg):
        if (compara_salida((simula_circuito((inputs[i]),(fenotipo(individuo)),(False))),(outputs[i]))==(1)):
            res = 1 + res
    if res==lg:
        print("Autoreparación completa")
    else:
        print("Coinciden " + str(res) + " de " + str(lg) + " salidas")
   

gen	nevals	mínimo	media	máximo
0  	10    	1.5   	2.1  	3     
1  	9     	1.75  	2.075	2.75  
2  	9     	0.75  	1.9  	2.75  
3  	10    	0.75  	1.7  	2.25  
4  	9     	1.5   	2    	2.25  
5  	9     	1.75  	2.05 	2.25  
6  	9     	1.75  	2.15 	2.25  
7  	9     	0.75  	1.95 	2.75  
8  	10    	1.75  	2.025	2.75  
9  	9     	1     	2.025	2.5   
10 	9     	1.25  	2.225	2.75  
11 	10    	1.5   	1.95 	2.75  
12 	10    	1.75  	2.05 	2.5   
13 	9     	0.75  	1.825	2.5   
14 	10    	1.5   	2.075	2.75  
15 	9     	1.25  	2.175	2.75  
16 	10    	1.75  	2.275	2.75  
17 	9     	1.75  	2.125	2.75  
18 	9     	1.5   	2.125	2.75  
19 	9     	1     	1.95 	2.75  
20 	9     	1.75  	2.15 	2.75  
Las tres mejor soluciones encontradas han sido:
[0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0] (3.0,)

 Lo que se traduce en el siguiente circuito: 
[[4. 4. 6. 3.]
 [1. 3. 3. 4.]
 [2. 3. 1. 5.]
 [3. 5. 2. 5.]]
[1][0] = Input[3] NAND Input[0]
[1][1] = Input[2] NAND Input[2]
[1][2] = Rota
[1][3] = Input[1] OR Input[2